//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.26 at 02:47:51 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeReceptor", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hxiloj.hacienda.receptor.dto;
